### PR TITLE
Custom Loading Screen, Icon + Title display, Greeting Slides, and more

### PR DESCRIPTION
**Pull request by Wyvest**
(also fixed workflow)

### CODE REVIEW

**Comment by KTibow** [comment]
nice, nice enough that i built it, which made me have a load of feedback
**welcome screen**:
- text is too small
- text has too low contrast (in general due to the background, and also in the bottom right image)
- transitions are too slow and fade to black instead of the main background
- wtf is this image
- buttons aren't aligned with the text image
- change `GREETING` to say something more informative about what the file does than `DO NOT DELETE THIS PLEASE <3`

**loading screen**:
image
- make the logo downscale better
- having an animated logo would be cool, here are some of my ideas:
  - bouncing around like the dvd logo
  - being squished/unsquished
  - pulsing (by zooming in/out)
  - color animation (color gradient or subtler gradient, like metal shining?)
- for the memory used meter:
  - you could try changing the text content?
  - improve contrast
  - imo it might look nice vertical

**ci**: you didn't fix ci, please revert your changes so this pr won't require fixing conflicts if my pr #54 merges (alternatively, add all changes from #54 into this pr)

**Comment by UnderscoreRayless** [comment]
What's the hudcaching screen? What triggers it

**Comment by KTibow** [comment]
> What's the hudcaching screen? What triggers it

it's part of the welcome tutorial, pops up the first time you launch with scc now

**Comment by Wyvest** [comment]
> nice, nice enough that i built it, which made me have a load of feedback **welcome screen**:
> 
>     * text is too small
> 
>     * text has too low contrast (in general due to the background, and also in the bottom right image)
> 
>     * transitions are too slow and fade to black instead of the main background
> 
>     * wtf is this image
> 
>     * buttons aren't aligned with the text image
> 
>     * change `GREETING` to say something more informative about what the file does than `DO NOT DELETE THIS PLEASE <3`
> 
> 
> **loading screen**: image
> 
>     * make the logo downscale better
> 
>     * having an animated logo would be cool, here are some of my ideas:
>       
>       * bouncing around like the dvd logo
>       * being squished/unsquished
>       * pulsing (by zooming in/out)
>       * color animation (color gradient or subtler gradient, like metal shining?)
> 
>     * for the memory used meter:
>       
>       * you could try changing the text content?
>       * improve contrast
>       * imo it might look nice vertical
> 
> 
> **ci**: you didn't fix ci, please revert your changes so this pr won't require fixing conflicts if my pr #54 merges (alternatively, add all changes from #54 into this pr)

fixed

**Comment by Wyvest** [comment]
> What's the hudcaching screen? What triggers it

Patcher

**Comment by Wyvest** [comment]
Ready for review.

**Comment by Wyvest** [comment]
image

**Pull request closed without merging**
