### PR TITLE
Main Menu tweaks

### PR DESCRIPTION
**Pull request by KTibow**
View diff

### CODE REVIEW

**Comment by KTibow** [comment]
Tested.
image

**Comment by UnderscoreRayless** [comment]
Can the skyclient discord server icon be used as a loading screen? And Zetvue's can be used for the menu as it's better as a logo, might also be good to wait as I think zetvue is redesigning it

**Comment by KTibow** [comment]
hmm imma try that

**Comment by KTibow** [comment]
closing bc we're using wyvest's repo now

**Pull request closed without merging**
